create extension if not exists pgcrypto;

create type public.user_role as enum ('free','premium','enterprise','owner');
create type public.key_status as enum ('active','revoked');
create type public.api_status as enum ('draft','published','disabled');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  full_name text,
  avatar_url text,
  role public.user_role not null default 'free',
  plan public.user_role not null default 'free',
  daily_limit bigint not null default 100,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.api_keys (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null default 'Default Key',
  key_prefix text not null,
  key_hash text not null unique,
  environment text not null default 'live',
  status public.key_status not null default 'active',
  last_used_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.api_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  api_key_id uuid references public.api_keys(id) on delete set null,
  endpoint text not null,
  method text not null,
  status_code int not null,
  response_ms int,
  created_at timestamptz default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique not null references public.profiles(id) on delete cascade,
  plan public.user_role not null default 'free',
  status text not null default 'active',
  current_period_end timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.api_catalog (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  category text not null default 'General',
  method text not null default 'GET',
  endpoint text not null,
  description text,
  requires_auth boolean not null default true,
  status public.api_status not null default 'draft',
  upstream_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.api_keys enable row level security;
alter table public.api_usage enable row level security;
alter table public.subscriptions enable row level security;
alter table public.api_catalog enable row level security;

drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles for select using (auth.uid() = id);
drop policy if exists keys_self on public.api_keys;
create policy keys_self on public.api_keys for select using (auth.uid() = user_id);
drop policy if exists usage_self on public.api_usage;
create policy usage_self on public.api_usage for select using (auth.uid() = user_id);
drop policy if exists subscriptions_self on public.subscriptions;
create policy subscriptions_self on public.subscriptions for select using (auth.uid() = user_id);
drop policy if exists catalog_public on public.api_catalog;
create policy catalog_public on public.api_catalog for select using (status = 'published');

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,username,role,plan,daily_limit)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email,'@',1)),
    'free','free',100
  ) on conflict (id) do nothing;
  insert into public.subscriptions(user_id,plan,status)
  values (new.id,'free','active') on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Setelah akun owner dibuat, jalankan:
-- update public.profiles set role='owner', plan='owner', daily_limit=999999999 where id='UUID_OWNER';
