"use client";
import {useState} from "react";
const blank={name:"",slug:"",category:"General",method:"GET",endpoint:"/api/v1/example",description:"",requires_auth:true,status:"draft",upstream_url:""};
export default function AdminApiManager({initialApis}){const [apis,setApis]=useState(initialApis);const [form,setForm]=useState(blank);const [editing,setEditing]=useState(null);const [saving,setSaving]=useState(false);
function update(k,v){setForm({...form,[k]:v})}
async function save(){setSaving(true);const r=await fetch("/api/admin/apis",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,id:editing})});const j=await r.json();if(j.status){setApis(editing?apis.map(x=>x.id===editing?j.data:x):[j.data,...apis]);setForm(blank);setEditing(null)}else alert(j.message);setSaving(false)}
async function remove(id){if(!confirm("Hapus API ini?"))return;const r=await fetch("/api/admin/apis?id="+id,{method:"DELETE"});const j=await r.json();if(j.status)setApis(apis.filter(x=>x.id!==id))}
function edit(x){setEditing(x.id);setForm({...blank,...x})}
return <div><div className="flex items-center justify-between"><div><h1 className="text-4xl font-black">API Manager</h1><p className="text-zinc-500">Tambah API ke katalog tanpa mengubah UI.</p></div><a href="/admin" className="rounded-xl border border-white/10 px-4 py-2">Back</a></div><div className="glass mt-7 rounded-2xl p-6"><h2 className="text-xl font-bold">{editing?"Edit API":"Add API"}</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{[["name","API Name"],["slug","Slug"],["category","Category"],["endpoint","Endpoint"],["description","Description"],["upstream_url","Upstream URL"]].map(([k,p])=><input key={k} value={form[k]||""} onChange={e=>update(k,e.target.value)} placeholder={p} className="rounded-xl border border-white/10 bg-white/5 p-3"/>)}</div><div className="mt-3 grid gap-3 md:grid-cols-3"><select value={form.method} onChange={e=>update("method",e.target.value)} className="rounded-xl border border-white/10 bg-white/5 p-3"><option>GET</option><option>POST</option><option>PUT</option><option>DELETE</option></select><select value={form.status} onChange={e=>update("status",e.target.value)} className="rounded-xl border border-white/10 bg-white/5 p-3"><option value="draft">draft</option><option value="published">published</option><option value="disabled">disabled</option></select><label className="flex items-center gap-2 rounded-xl border border-white/10 p-3"><input type="checkbox" checked={!!form.requires_auth} onChange={e=>update("requires_auth",e.target.checked)}/> Requires API Key</label></div><button onClick={save} disabled={saving} className="mt-4 rounded-xl bg-violet-600 px-5 py-3 font-bold">{saving?"Saving…":editing?"Update API":"Publish API"}</button></div><div className="mt-6 space-y-3">{apis.map(a=><div key={a.id} className="glass rounded-2xl p-5"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><div className="text-xs text-violet-300">{a.method} · {a.status}</div><h3 className="mt-1 text-xl font-bold">{a.name}</h3><code className="text-sm text-zinc-500">{a.endpoint}</code><p className="mt-2 text-sm text-zinc-400">{a.description}</p></div><div className="flex gap-2"><button onClick={()=>edit(a)} className="rounded-xl border border-white/10 px-4 py-2">Edit</button><button onClick={()=>remove(a.id)} className="rounded-xl bg-red-500/10 px-4 py-2 text-red-300">Delete</button></div></div></div>)}</div></div>}
